#!/bin/sh

ln -s  ../src/mpn/generic/add.c ./add.c
ln -s  ../src/mpn/generic/add_1.c ./add_1.c
ln -s  ../src/mpn/x86_64/core2/aors_n.asm ./add_n.asm
ln -s  ../src/mpn/x86_64/addaddmul_1msb0.asm ./addaddmul_1msb0.asm
ln -s  ../src/mpn/x86_64/core2/aorslsh1_n.asm ./addlsh1_n.asm
ln -s  ../src/mpn/x86_64/aorrlsh2_n.asm ./addlsh2_n.asm
ln -s  ../src/mpn/x86_64/aorrlsh_n.asm ./addlsh_n.asm
ln -s  ../src/mpn/x86_64/core2/aorsmul_1.asm ./addmul_1.asm
ln -s  ../src/mpn/x86_64/addmul_2.asm ./addmul_2.asm
ln -s  ../src/mpn/x86_64/logops_n.asm ./and_n.asm
ln -s  ../src/mpn/x86_64/logops_n.asm ./andn_n.asm
ln -s  ../src/mpn/x86_64/bdiv_dbm1c.asm ./bdiv_dbm1c.asm
ln -s  ../src/mpn/generic/bdiv_q.c ./bdiv_q.c
ln -s  ../src/mpn/x86_64/bdiv_q_1.asm ./bdiv_q_1.asm
ln -s  ../src/mpn/generic/bdiv_qr.c ./bdiv_qr.c
ln -s  ../src/mpn/generic/binvert.c ./binvert.c
ln -s  ../src/mpn/generic/cmp.c ./cmp.c
ln -s  ../src/mpn/x86_64/com.asm ./com.asm
ln -s  ../src/mpn/x86_64/copyd.asm ./copyd.asm
ln -s  ../src/mpn/x86_64/copyi.asm ./copyi.asm
ln -s  ../src/mpn/generic/dcpi1_bdiv_q.c ./dcpi1_bdiv_q.c
ln -s  ../src/mpn/generic/dcpi1_bdiv_qr.c ./dcpi1_bdiv_qr.c
ln -s  ../src/mpn/generic/dcpi1_div_q.c ./dcpi1_div_q.c
ln -s  ../src/mpn/generic/dcpi1_div_qr.c ./dcpi1_div_qr.c
ln -s  ../src/mpn/generic/dcpi1_divappr_q.c ./dcpi1_divappr_q.c
ln -s  ../src/mpn/generic/div_q.c ./div_q.c
ln -s  ../src/mpn/x86_64/dive_1.asm ./dive_1.asm
ln -s  ../src/mpn/generic/diveby3.c ./diveby3.c
ln -s  ../src/mpn/generic/divexact.c ./divexact.c
ln -s  ../src/mpn/generic/divis.c ./divis.c
ln -s  ../src/mpn/generic/divrem.c ./divrem.c
ln -s  ../src/mpn/x86_64/divrem_1.asm ./divrem_1.asm
ln -s  ../src/mpn/x86_64/divrem_2.asm ./divrem_2.asm
ln -s  ../src/mpn/generic/dump.c ./dump.c
ln -s  ../src/mpn/generic/fib2_ui.c ./fib2_ui.c
ln -s  ../src/mpn/generic/gcd.c ./gcd.c
ln -s  ../src/mpn/x86_64/gcd_1.asm ./gcd_1.asm
ln -s  ../src/mpn/generic/gcd_lehmer.c ./gcd_lehmer.c
ln -s  ../src/mpn/generic/gcd_subdiv_step.c ./gcd_subdiv_step.c
ln -s  ../src/mpn/generic/gcdext.c ./gcdext.c
ln -s  ../src/mpn/generic/gcdext_1.c ./gcdext_1.c
ln -s  ../src/mpn/generic/gcdext_lehmer.c ./gcdext_lehmer.c
ln -s  ../src/mpn/generic/gcdext_subdiv_step.c ./gcdext_subdiv_step.c
ln -s  ../src/mpn/generic/get_d.c ./get_d.c
ln -s  ../src/mpn/generic/get_str.c ./get_str.c
ln -s  ../src/mpn/x86_64/popham.asm ./hamdist.asm
ln -s  ../src/mpn/generic/hgcd.c ./hgcd.c
ln -s  ../src/mpn/generic/hgcd2.c ./hgcd2.c
ln -s  ../src/mpn/generic/invert.c ./invert.c
ln -s  ../src/mpn/x86_64/invert_limb.asm ./invert_limb.asm
ln -s  ../src/mpn/generic/invertappr.c ./invertappr.c
ln -s  ../src/mpn/x86_64/logops_n.asm ./ior_n.asm
ln -s  ../src/mpn/x86_64/logops_n.asm ./iorn_n.asm
ln -s  ../src/mpn/generic/jacbase.c ./jacbase.c
ln -s  ../src/mpn/x86_64/core2/lshift.asm ./lshift.asm
ln -s  ../src/mpn/x86_64/core2/lshiftc.asm ./lshiftc.asm
ln -s  ../src/mpn/generic/matrix22_mul.c ./matrix22_mul.c
ln -s  ../src/mpn/generic/mod_1.c ./mod_1.c
ln -s  ../src/mpn/generic/mod_1_1.c ./mod_1_1.c
ln -s  ../src/mpn/generic/mod_1_2.c ./mod_1_2.c
ln -s  ../src/mpn/generic/mod_1_3.c ./mod_1_3.c
ln -s  ../src/mpn/x86_64/mod_1_4.asm ./mod_1_4.asm
ln -s  ../src/mpn/x86_64/mod_34lsub1.asm ./mod_34lsub1.asm
ln -s  ../src/mpn/x86_64/mode1o.asm ./mode1o.asm
ln -s  ../src/mpn/generic/mu_bdiv_q.c ./mu_bdiv_q.c
ln -s  ../src/mpn/generic/mu_bdiv_qr.c ./mu_bdiv_qr.c
ln -s  ../src/mpn/generic/mu_div_q.c ./mu_div_q.c
ln -s  ../src/mpn/generic/mu_div_qr.c ./mu_div_qr.c
ln -s  ../src/mpn/generic/mu_divappr_q.c ./mu_divappr_q.c
ln -s  ../src/mpn/generic/mul.c ./mul.c
ln -s  ../src/mpn/x86_64/mul_1.asm ./mul_1.asm
ln -s  ../src/mpn/x86_64/mul_2.asm ./mul_2.asm
ln -s  ../src/mpn/x86_64/mul_basecase.asm ./mul_basecase.asm
ln -s  ../src/mpn/generic/mul_fft.c ./mul_fft.c
ln -s  ../src/mpn/generic/mul_n.c ./mul_n.c
ln -s  ../src/mpn/generic/mullo_basecase.c ./mullo_basecase.c
ln -s  ../src/mpn/generic/mullo_n.c ./mullo_n.c
ln -s  ../src/mpn/generic/mulmod_bnm1.c ./mulmod_bnm1.c
ln -s  ../src/mpn/x86_64/logops_n.asm ./nand_n.asm
ln -s  ../src/mpn/generic/neg.c ./neg.c
ln -s  ../src/mpn/x86_64/logops_n.asm ./nior_n.asm
ln -s  ../src/mpn/generic/nussbaumer_mul.c ./nussbaumer_mul.c
ln -s  ../src/mpn/generic/perfpow.c ./perfpow.c
ln -s  ../src/mpn/generic/perfsqr.c ./perfsqr.c
ln -s  ../src/mpn/x86_64/core2/popcount.asm ./popcount.asm
ln -s  ../src/mpn/generic/pow_1.c ./pow_1.c
ln -s  ../src/mpn/generic/powlo.c ./powlo.c
ln -s  ../src/mpn/generic/powm.c ./powm.c
ln -s  ../src/mpn/generic/powm_sec.c ./powm_sec.c
ln -s  ../src/mpn/generic/pre_mod_1.c ./pre_mod_1.c
ln -s  ../src/mpn/generic/random.c ./random.c
ln -s  ../src/mpn/generic/random2.c ./random2.c
ln -s  ../src/mpn/x86_64/redc_1.asm ./redc_1.asm
ln -s  ../src/mpn/generic/redc_1_sec.c ./redc_1_sec.c
ln -s  ../src/mpn/generic/redc_2.c ./redc_2.c
ln -s  ../src/mpn/generic/redc_n.c ./redc_n.c
ln -s  ../src/mpn/generic/remove.c ./remove.c
ln -s  ../src/mpn/generic/rootrem.c ./rootrem.c
ln -s  ../src/mpn/x86_64/aorrlsh1_n.asm ./rsblsh1_n.asm
ln -s  ../src/mpn/x86_64/aorrlsh2_n.asm ./rsblsh2_n.asm
ln -s  ../src/mpn/x86_64/aorrlsh_n.asm ./rsblsh_n.asm
ln -s  ../src/mpn/x86_64/rsh1aors_n.asm ./rsh1add_n.asm
ln -s  ../src/mpn/x86_64/rsh1aors_n.asm ./rsh1sub_n.asm
ln -s  ../src/mpn/x86_64/core2/rshift.asm ./rshift.asm
ln -s  ../src/mpn/generic/sbpi1_bdiv_q.c ./sbpi1_bdiv_q.c
ln -s  ../src/mpn/generic/sbpi1_bdiv_qr.c ./sbpi1_bdiv_qr.c
ln -s  ../src/mpn/generic/sbpi1_div_q.c ./sbpi1_div_q.c
ln -s  ../src/mpn/generic/sbpi1_div_qr.c ./sbpi1_div_qr.c
ln -s  ../src/mpn/generic/sbpi1_divappr_q.c ./sbpi1_divappr_q.c
ln -s  ../src/mpn/generic/scan0.c ./scan0.c
ln -s  ../src/mpn/generic/scan1.c ./scan1.c
ln -s  ../src/mpn/generic/set_str.c ./set_str.c
ln -s  ../src/mpn/generic/sqr.c ./sqr.c
ln -s  ../src/mpn/x86_64/sqr_basecase.asm ./sqr_basecase.asm
ln -s  ../src/mpn/generic/sqrmod_bnm1.c ./sqrmod_bnm1.c
ln -s  ../src/mpn/generic/sqrtrem.c ./sqrtrem.c
ln -s  ../src/mpn/generic/sub.c ./sub.c
ln -s  ../src/mpn/generic/sub_1.c ./sub_1.c
ln -s  ../src/mpn/x86_64/core2/aors_n.asm ./sub_n.asm
ln -s  ../src/mpn/generic/subcnd_n.c ./subcnd_n.c
ln -s  ../src/mpn/x86_64/core2/aorslsh1_n.asm ./sublsh1_n.asm
ln -s  ../src/mpn/x86_64/core2/aorsmul_1.asm ./submul_1.asm
ln -s  ../src/mpn/generic/tdiv_qr.c ./tdiv_qr.c
ln -s  ../src/mpn/generic/toom22_mul.c ./toom22_mul.c
ln -s  ../src/mpn/generic/toom2_sqr.c ./toom2_sqr.c
ln -s  ../src/mpn/generic/toom32_mul.c ./toom32_mul.c
ln -s  ../src/mpn/generic/toom33_mul.c ./toom33_mul.c
ln -s  ../src/mpn/generic/toom3_sqr.c ./toom3_sqr.c
ln -s  ../src/mpn/generic/toom42_mul.c ./toom42_mul.c
ln -s  ../src/mpn/generic/toom43_mul.c ./toom43_mul.c
ln -s  ../src/mpn/generic/toom44_mul.c ./toom44_mul.c
ln -s  ../src/mpn/generic/toom4_sqr.c ./toom4_sqr.c
ln -s  ../src/mpn/generic/toom52_mul.c ./toom52_mul.c
ln -s  ../src/mpn/generic/toom53_mul.c ./toom53_mul.c
ln -s  ../src/mpn/generic/toom62_mul.c ./toom62_mul.c
ln -s  ../src/mpn/generic/toom63_mul.c ./toom63_mul.c
ln -s  ../src/mpn/generic/toom6_sqr.c ./toom6_sqr.c
ln -s  ../src/mpn/generic/toom6h_mul.c ./toom6h_mul.c
ln -s  ../src/mpn/generic/toom8_sqr.c ./toom8_sqr.c
ln -s  ../src/mpn/generic/toom8h_mul.c ./toom8h_mul.c
ln -s  ../src/mpn/generic/toom_couple_handling.c ./toom_couple_handling.c
ln -s  ../src/mpn/generic/toom_eval_dgr3_pm1.c ./toom_eval_dgr3_pm1.c
ln -s  ../src/mpn/generic/toom_eval_dgr3_pm2.c ./toom_eval_dgr3_pm2.c
ln -s  ../src/mpn/generic/toom_eval_pm1.c ./toom_eval_pm1.c
ln -s  ../src/mpn/generic/toom_eval_pm2.c ./toom_eval_pm2.c
ln -s  ../src/mpn/generic/toom_eval_pm2exp.c ./toom_eval_pm2exp.c
ln -s  ../src/mpn/generic/toom_eval_pm2rexp.c ./toom_eval_pm2rexp.c
ln -s  ../src/mpn/generic/toom_interpolate_12pts.c ./toom_interpolate_12pts.c
ln -s  ../src/mpn/generic/toom_interpolate_16pts.c ./toom_interpolate_16pts.c
ln -s  ../src/mpn/generic/toom_interpolate_5pts.c ./toom_interpolate_5pts.c
ln -s  ../src/mpn/generic/toom_interpolate_6pts.c ./toom_interpolate_6pts.c
ln -s  ../src/mpn/generic/toom_interpolate_7pts.c ./toom_interpolate_7pts.c
ln -s  ../src/mpn/generic/toom_interpolate_8pts.c ./toom_interpolate_8pts.c
ln -s  ../src/mpn/generic/trialdiv.c ./trialdiv.c
ln -s  ../src/mpn/x86_64/logops_n.asm ./xnor_n.asm
ln -s  ../src/mpn/x86_64/logops_n.asm ./xor_n.asm
ln -s  ../src/mpn/generic/zero.c ./zero.c
